//
//  ListageInteractor.swift
//  InstalandoVIP
//
//  Created by Marcel Leite de Farias on 04/04/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListageBusinessLogic
{
  func doSomething(request: Listage.Something.Request)
}

protocol ListageDataStore
{
  //var name: String { get set }
}

class ListageInteractor: ListageBusinessLogic, ListageDataStore
{
  var presenter: ListagePresentationLogic?
  var worker: ListageWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Listage.Something.Request)
  {
    worker = ListageWorker()
    worker?.doSomeWork()
    
    let response = Listage.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
