//
//  ListagePresenter.swift
//  InstalandoVIP
//
//  Created by Marcel Leite de Farias on 04/04/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListagePresentationLogic
{
  func presentSomething(response: Listage.Something.Response)
}

class ListagePresenter: ListagePresentationLogic
{
  weak var viewController: ListageDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Listage.Something.Response)
  {
    let viewModel = Listage.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
