//
//  CoinsListRouter.swift
//  MarketCoins
//
//  Created by Marcel Leite de Farias on 11/04/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CoinsListRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol CoinsListDataPassing
{
  var dataStore: CoinsListDataStore? { get }
}

class CoinsListRouter: NSObject, CoinsListRoutingLogic, CoinsListDataPassing
{
  weak var viewController: CoinsListViewController?
  var dataStore: CoinsListDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CoinsListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CoinsListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
