//
//  CoinsListPresenter.swift
//  MarketCoins
//
//  Created by Marcel Leite de Farias on 10/04/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoinsListPresentationLogic
{
  func presentSomething(response: CoinsList.Something.Response)
}

class CoinsListPresenter: CoinsListPresentationLogic
{
  weak var viewController: CoinsListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CoinsList.Something.Response)
  {
    let viewModel = CoinsList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
